name: 'Build and Deploy to Cloud Run'

on:
  # Manual trigger
  workflow_dispatch:

env:
  PROJECT_ID: 'pulse-439215'
  REGION: 'europe-west2'
  SERVICE: 'ingest-pipeline'
  DOCKER_REGISTRY_NAME: 'pulse'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/594993328978/locations/global/workloadIdentityPools/github-actions/providers/pulse-repo'
  SERVICE_ACCOUNT_EMAIL: 'github-actions@pulse-439215.iam.gserviceaccount.com'
jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2' # google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          service_account: '${{ env.SERVICE_ACCOUNT_EMAIL }}'
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

      - name: 'Print Authentication Outputs'
        run: |
          echo "Access Token: ${{ steps.auth.outputs.access_token }}"
          echo "Token Expiry: ${{ steps.auth.outputs.expires_at }}"

      - name: 'Check Active GCP Account'
        run: |
          gcloud auth list